# Generated by Django 4.1 on 2023-05-02 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="모델",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=45, null=True)),
                ("모델이름", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="유저",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("닉네임", models.CharField(max_length=10)),
                ("아이디", models.CharField(max_length=45)),
                ("비밀번호", models.CharField(max_length=45)),
                ("가입날짜", models.DateTimeField(auto_now_add=True)),
                ("is_super", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="유저_import_모델",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "모델_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="word_e_back.모델"
                    ),
                ),
                (
                    "유저_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="word_e_back.유저"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
