# Generated by Django 4.1 on 2023-05-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0002_모델_유저_유저_import_모델_delete_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="유저_import_모델",
            old_name="모델_id",
            new_name="모델",
        ),
        migrations.RenameField(
            model_name="유저_import_모델",
            old_name="유저_id",
            new_name="유저",
        ),
    ]
