# Generated by Django 4.1 on 2023-05-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0003_rename_모델_id_유저_import_모델_모델_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="게시물",
            fields=[
                (
                    "모델",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="word_e_back.모델",
                    ),
                ),
                ("제목", models.CharField(max_length=45)),
                ("글내용_모델", models.TextField(blank=True, null=True)),
                ("글내용_데이터", models.TextField(blank=True, null=True)),
                ("작성일", models.DateTimeField(auto_now_add=True)),
                ("수정일", models.DateTimeField(auto_now=True)),
                (
                    "유저",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="word_e_back.유저"
                    ),
                ),
            ],
        ),
    ]
