# Generated by Django 4.1 on 2023-05-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0005_태그_데이터셋"),
    ]

    operations = [
        migrations.AlterField(
            model_name="유저",
            name="닉네임",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="유저",
            name="아이디",
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name="태그",
            name="태그이름",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
