# Generated by Django 4.1 on 2023-05-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0008_remove_태그_모델"),
    ]

    operations = [
        migrations.AlterField(
            model_name="태그",
            name="태그이름",
            field=models.CharField(max_length=20),
        ),
    ]
