# Generated by Django 4.1 on 2023-05-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0010_alter_게시물_모델"),
    ]

    operations = [
        migrations.RenameField(
            model_name="데이터셋",
            old_name="게시물",
            new_name="모델",
        ),
        migrations.RenameField(
            model_name="태그",
            old_name="게시물",
            new_name="모델",
        ),
        migrations.AlterField(
            model_name="게시물",
            name="모델",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="word_e_back.모델",
            ),
        ),
    ]
