# Generated by Django 4.1 on 2023-05-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0015_alter_태그_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="태그2",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("태그이름", models.CharField(max_length=20)),
                (
                    "모델",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="word_e_back.게시물",
                    ),
                ),
            ],
        ),
    ]
