# Generated by Django 4.1 on 2023-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0016_태그2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="태그2",
            name="ID",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
