# Generated by Django 4.1 on 2023-05-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0020_alter_게시물_제목_alter_데이터셋_path_alter_모델_path_delete_태그"),
    ]

    operations = [
        migrations.AlterField(
            model_name="데이터셋",
            name="모델",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="word_e_back.모델"
            ),
        ),
    ]
