# Generated by Django 4.1 on 2023-05-02 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0004_게시물"),
    ]

    operations = [
        migrations.CreateModel(
            name="태그",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("태그이름", models.CharField(max_length=20)),
                (
                    "게시물",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="word_e_back.게시물",
                    ),
                ),
                (
                    "모델",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="word_e_back.모델"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="데이터셋",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=45, null=True)),
                ("데이터", models.TextField(null=True)),
                (
                    "게시물",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="word_e_back.게시물",
                    ),
                ),
                (
                    "모델",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="word_e_back.모델"
                    ),
                ),
            ],
        ),
    ]
