# Generated by Django 4.1 on 2023-05-02 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0009_alter_태그_태그이름"),
    ]

    operations = [
        migrations.AlterField(
            model_name="게시물",
            name="모델",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="word_e_back.모델",
            ),
        ),
    ]
