# Generated by Django 4.1 on 2023-05-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0011_rename_게시물_데이터셋_모델_rename_게시물_태그_모델_alter_게시물_모델"),
    ]

    operations = [
        migrations.AddField(
            model_name="유저",
            name="토큰",
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="유저",
            name="토큰생성시간",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
