# Generated by Django 4.1 on 2023-05-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0017_alter_태그2_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="태그2",
        ),
    ]
