# Generated by Django 4.1 on 2023-05-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0018_delete_태그2"),
    ]

    operations = [
        migrations.CreateModel(
            name="태그모음",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("태그이름", models.CharField(max_length=20)),
                (
                    "모델",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="word_e_back.게시물",
                    ),
                ),
            ],
        ),
    ]
