# Generated by Django 4.1 on 2023-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_e_back", "0019_태그모음"),
    ]

    operations = [
        migrations.AlterField(
            model_name="게시물",
            name="제목",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="데이터셋",
            name="path",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="모델",
            name="path",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name="태그",
        ),
    ]
